### ISSUE TITLE
CoC はメニューなしです。

### ISSUE THREAD

**Issue by martinheidegger** [nodefest/nodefest.github.com#165]
(CoC has no menu)

[CoC](https://nodefest.jp/2018/coc.html) のページにはメニューを追加する。
Add the navigation to the [CoC](https://nodefest.jp/2018/coc.html) Page.

**Comment by AndrewZamora** [comment]
I will give this one a shot ✋🏽.

**Comment by martinheidegger** [comment]
Fixed in #166
