### ISSUE TITLE
TICKETSを押してもGET YOUR TICKETSへスクロールしない

### ISSUE THREAD

**Issue by Leko** [nodefest/nodefest.github.com#170]
URL: https://nodefest.jp/2018/
のTICKETSボタンを押しても、GET YOUR TICKETSへスクロールせず、画面上部に戻ってしまう

macOS Chrome Version 70.0.3538.77 (Official Build) (64-bit)

![kapture 2018-11-16 at 22 32 16](https://user-images.githubusercontent.com/1424963/48624348-843f5a00-e9ef-11e8-9ebc-623a7b70b9c4.gif)

**Comment by leader22** [comment]
Last year, we did not have an issue like this.

Thus... @martinheidegger 🙏

**Comment by Leko** [comment]
We should use `click` event, not `hashchange` to implement smooth scroll.
I think that can't prevent scroll on hashchange.
