### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by watilde** [nodefest/nodefest.github.com#53]
リンクはられてないので大丈夫かとは思うんですが、手打ちでアクセスしたらhttpsでエラー出てたので共有です
- https://nodefest.jp/2016/

**Comment by myakura** [comment]
これって、カスタムドメインなGitHub Pagesでホストしてるからですよね…

**Comment by tgfjt** [comment]
Cloudflare の Universal SSL を使うとか…？

**Comment by tgfjt** [comment]
Netlify で Let's Encrypt 使って HTTPS にできるから良いかも

**Comment by leader22** [comment]
Now, we're on https!
