### ISSUE TITLE
公開後TODO

### ISSUE THREAD

**Issue by leader22** [nodefest/nodefest.github.com#61]
- [x] 会場までのアクセス紹介を追加
- [x] 会場入り口周辺の写真素材ほしい。自分で撮るかも。
- [x] メディア向けの文言追加する？
- [x] 公式Twitterの案内、ハッシュタグなど
- [x] GoogleMapのマイマップつくる？（両会場の配置されたもの）

**Comment by kysnm** [comment]
> dots.の入り口周辺の写真素材ほしい。自分で撮るかも。

Google  map にそれっぽい画像はあるので一応報告

https://goo.gl/maps/tHECQt7yt7L2
https://goo.gl/maps/utShe8S1wEx
