### ISSUE TITLE
文字が読み辛い

### ISSUE THREAD

**Issue by abouthiroppy** [nodefest/nodefest.github.com#68]
`それぞれの日程ごとにお申し込みください。`  の途中から背景と色が被ってしまい少し見辛いかなと思いましたので色の変更等を検討して頂けるとありがたいです :pray:

![2016-10-12 13 54 09](https://cloud.githubusercontent.com/assets/3367801/19297828/651a0e8a-9083-11e6-9ddd-5f703a0b6d1b.png)

**Comment by hiloki** [comment]
@abouthiroppy 
#70 にて修正しました、報告ありがとうございます！
