### ISSUE TITLE
背景と重なり読み辛い

### ISSUE THREAD

**Issue by abouthiroppy** [nodefest/nodefest.github.com#78]
http://nodefest.jp/2016/venues.html
右上の「おおきな地図で見る」と 「イベント&コミュニティスペース dots.」周り
![2016-10-28 15 46 54](https://cloud.githubusercontent.com/assets/3367801/19797403/d7dae512-9d25-11e6-89a8-f397b7e3ced3.png)

http://nodefest.jp/2016/coc.html
本文左上
![2016-10-28 15 47 16](https://cloud.githubusercontent.com/assets/3367801/19797419/e3a57128-9d25-11e6-9f2a-1c9c17905da2.png)

**Comment by hiloki** [comment]
@abouthiroppy
閲覧環境について教えていただけますか？（OS/ブラウザ/スクリーンサイズなど）

**Comment by abouthiroppy** [comment]
OS: OS X El Capitan(mac)
ディスプレイ: Thunderbolt Display(27インチ)
ブラウザ: chrome  54.0.2840.71(最新)

です。

**Comment by hiloki** [comment]
@abouthiroppy 
ありがとうございます、おそらく問題は解消したかと。

**Comment by abouthiroppy** [comment]
@hiloki 確認しました！ありがとうございます！
