### ISSUE TITLE
法政大学を使う際にはスポンサーロゴを入れることを失念しておりました。

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodefest/nodefest.github.com#91]
法政大学では利用する際にスポンサーロゴを入れる必要があります。どなたかBronzeの下に会場スポンサーを作っていただけないでしょうか？そこに下記添付したロゴを入れてもらいたいです。

> また、サイトの方をもう用意されたようですが、規約にあります
> 情報科学部サイトへのリンクを後援・スポンサーなど、
> 適当な枠組みでお願いいたします。
>
> 法政大学情報科学部
> http://cis.hosei.ac.jp/
> 必要であれば使用するようにロゴファイルを添付します。
> 上記が満たされないと施設貸与ができなくなります。

一旦添付しておきます。もしもわからないことがあれば教えてください。よろしくお願いします。

![hosei university](https://user-images.githubusercontent.com/555645/31114581-c5217388-a859-11e7-94d5-596487b7890c.jpg)

**Comment by hiloki** [comment]
fixed #92
