### ISSUE TITLE
バナーのリサイズするぞ

### ISSUE THREAD

**Issue by hiloki** [nodefest/nodefest.github.com#93]
各社からいただいたバナーのサイズがばらばらなので、ザブトンを敷いて揃える。

**Comment by hiloki** [comment]
mobile相当のときに、SilverよりBronzeが大きくなる計算になってるので修正す。

**Comment by leader22** [comment]
#95 

↑こういうのもあるので、全体的にサイズの調整が必要な場合はあわせてよろしくお願いします！

**Comment by watilde** [comment]
当たってるclassが`.sponsors-grade` で、SilverとVenueは同じサイズになってますよね今たぶん。もしそうなら、このままでいいと思います :)

**Comment by hiloki** [comment]
@watilde 同じサイズで大丈夫！このissueはcloseします。
